# Generated by Django 3.0.5 on 2021-03-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsernamePasswordService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=15)),
                ('pass_word', models.CharField(max_length=20)),
            ],
        ),
    ]
