# Generated by Django 3.0.5 on 2021-04-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernamepasswordservice',
            old_name='pass_word',
            new_name='password',
        ),
    ]
