# Generated by Django 3.0.5 on 2021-05-10 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_storage', '0002_auto_20210407_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernamepasswordservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
