# Generated by Django 3.0.5 on 2021-05-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_storage', '0003_usernamepasswordservice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernamepasswordservice',
            old_name='password',
            new_name='secret',
        ),
    ]
